.Dd November 17, 2023
.Dt INTRO-SSJ-TUKUBAI 1
.Os "ShellShoccar-Jpn Tukubai"
.Sh NAME
.Nm intro-ssj-tukubai
.Nd Introduction to ShellShoccar-jpn/Open-usp-Tukubai
.Sh DESCRIPTION
The
.Nm Open-usp-Tukubai ,
which is the open source version of
.Nm "usp Tukubai"
from
.Lk https://www.usp-lab.com/opinion.html "Universal Shell Programming Laboratory"
is a set of fundamental commands for the
.Nm Unicage :
software development method that de
.Pp
TODO
.Sh HISTORY
Originally, the
.Nm Open-usp-Tukubai
used to be developed by
.Lk "https://github.com/usp-engineers-community/Open-usp-Tukubai" "usp engineers community"
in three programming languages: Python, shellscript, and Haskell since 2012.
In 2015 ShellShoccar-jpn forked the project.
.Sh SEE ALSO
.Ss Tukubai commands implemented in ShellShoccar-jpn's fork
.Xr calclock 1 ,
.Xr cgi-name 1 ,
.Xr cjoin0 1 ,
.Xr cjoin1 1 ,
.Xr cjoin2 1 ,
.Xr comma 1 ,
.Xr count 1 ,
.Xr ctail 1 ,
.Xr delf 1 ,
.Xr filehame 1 ,
.Xr formhame 1 ,
.Xr getfirst 1 ,
.Xr getlast 1 ,
.Xr gyo 1 ,
.Xr han 1 ,
.Xr keta 1 ,
.Xr keycut 1 ,
.Xr mime-read 1 ,
.Xr mojihame 1 ,
.Xr mojihame-h 1 ,
.Xr mojihame-l 1 ,
.Xr mojihame-p 1 ,
.Xr nameread 1 ,
.Xr plus 1 ,
.Xr retu 1 ,
.Xr self 1 ,
.Xr sm2 1 ,
.Xr sm4 1 ,
.Xr sm5 1 ,
.Xr sorter 1 ,
.Xr tarr 1 ,
.Xr tateyoko 1 ,
.Xr tcat 1 ,
.Xr up3 1 ,
.Xr yarr 1 ,
.Xr ycat 1 ,
.Xr ysum 1 ,
.Xr zen 1
.Ss Data format
.Xr field-format 5 ,
.Xr master-file 5 ,
.Xr name-file 5 ,
.Xr name-format 5 ,
.Xr tag-format 5 ,
.Xr transaction-file 5
