#!/bin/sh

######################################################################
#
# HAN - Converter From "Zenkaku" (Japanese Fullwidth) Characters To
#       "Hankaku" (Japanese Halfwidth) Characters
#
# USAGE: han <file>
#        han [+<n>h] <f1> <f2> ... <file>
#        han -d <string>
#
#        <fn> .... field number you want to convert (All characters will
#                  be converted when you set no <fn> arguments)
#        <file> .. Text file you want to convert
#        <string>  It will be explained in -d option
#        -d ...... Direct Mode :
#                  It make this command regard the last argument (<string>)
#                  as a field formatted string instead of <file>
#        +<n>h ... Regards the top <n> lines as comment and Print without
#                  converting
#
# Designed originally by Nobuaki Tounaka
# Written by Shell-Shoccar Japan (@shellshoccarjpn) on 2017-08-26
#
# This is a public-domain software (CC0). It means that all of the
# people can use this for any purposes with no restrictions at all.
# By the way, we are fed up with the side effects which are brought
# about by the major licenses.
#
######################################################################


######################################################################
# Initial Configuration
######################################################################

# === Initialize shell environment ===================================
set -u
umask 0022
export LC_ALL=C
type command >/dev/null 2>&1 && type getconf >/dev/null 2>&1 &&
export PATH="$(command -p getconf PATH)${PATH+:}${PATH-}"
export UNIX_STD=2003  # to make HP-UX conform to POSIX

# === Define the functions for printing usage and error message ======
print_usage_and_exit () {
  cat <<-USAGE 1>&2
	Usage: ${0##*/} <file>
	       ${0##*/} [+<n>h] <f1> <f2> ... <file>
	       ${0##*/} -d <string>
	Args    : <fn> .... field number you want to convert (All characters will
	                    be converted when you set no <fn> arguments)
	          <file> .. Text file you want to convert
	          <string>  It will be explained in -d option
	Options : -d ...... Direct Mode :
	                    It make this command regard the last argument (<string>)
	                    as a field formatted string instead of <file>
	          +<n>h ... Regards the top <n> lines as comment and Print without
	                    converting
	Version : 2017-08-26 13:54:53 JST
	          Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands/UTF-8)
	USAGE
  exit 1
}
error_exit() {
  ${2+:} false && echo "${0##*/}: $2" 1>&2
  exit $1
}


######################################################################
# Parse Arguments
######################################################################

# === Get the options and the filepath ===============================
# --- initialize option parameters -----------------------------------
directmode=0
directstr=''
awkc0=''
file=''
fldnums=''
all_fields=0
use_stdin=0
opt_part=1
opth=0
#
# --- get them -------------------------------------------------------
case "$#${1:-}" in 1-h|1-v|1--help|1--version) print_usage_and_exit;; esac
i=0
for arg in ${1+"$@"}; do
  i=$((i+1))
  fldnum=''
  # direct mode processing
  if   [ $opt_part -ne 0 ] && [ "_$arg" = '_-d'        ]; then
    directmode=1
    continue
  elif [ $opt_part -ne 0 ] && [ "_$arg" != "_${arg#+}" ]; then
    s=$(printf '%s\n' "$arg" | sed 's/^+\([0-9]*\)h$/\1/')
    [ "_$s" != "_$arg" ] || print_usage_and_exit
    [ -z "$s"          ] && { opth=1; continue; }
    opth=$(expr $s + 0)
    continue
  fi
  opt_part=0
  if [ $i -eq $# ] && [ $directmode -ne 0 ]; then
    directstr=$arg
    break
  fi
  # separate arg to arg1, arg2
  arg1=${arg%%/*}
  arg2=${arg##*/}
  if [ "_${arg1}/${arg2}" != "_$arg" ] || [ -z "$arg1" ] || [ -z "$arg2" ]; then
    arg1=$arg
    arg2=''
  fi
  # check both
  j=0
  for s in $arg1 $arg2; do
    if printf '%s\n' "$s" | grep -q '^[0-9]\{1,\}$'; then
      j=$((j+1))
      if [ "$s" -eq 0 ]; then
        all_fields=1
      fi
    elif printf '%s\n' "$s" | grep -Eq '^(NF|NF-[0-9]+)$'; then
      j=$((j+1))
    fi
  done
  if [ $j -eq 2 ] || ([ $j -eq 1 ] && [ -z "$arg2" ]); then
    fldnums="$fldnums $arg"
    continue
  fi
  # perhaps, this argument is a filename
  if [ $# -eq $i ]; then
    file=$arg
    continue
  fi
  # otherwise, it is a invalid argument
  print_usage_and_exit
done
# (if you want to regard no fldnums as all, set all_fields=1 instead of exit)
[ -n "$fldnums" ] || all_fields=1
if [ $directmode -ne 0 ]; then
  [ -n "$directstr" ] || print_usage_and_exit
  file=''
else
  [ -n "$file" ] || file='-'
  case "$file" in
     -|/dev/stdin|/dev/fd/0|/proc/self/fd/0) use_stdin=$((use_stdin+1));;
  esac
  if   [ ! -f "$file"     ] &&
       [ ! -c "$file"     ] &&
       [ ! -p "$file"     ] &&
       [ "_$file" != '_-' ]  ; then
    print_usage_and_exit
  elif [ ! -r "$file" ] && [ "_$file" != '_-' ]; then
    error_exit 1 'Cannot open the file'
  fi
fi
case "$file" in ''|-|/*|./*|../*) :;; *) file="./$file";; esac


######################################################################
# Prepare for the Main Routine
######################################################################

# === Generate the partial code for AWK ==============================
if [ $all_fields -eq 0 ]; then
  awkc0=$(echo "$fldnums"                           |
          sed 's/^0\{1,\}\([0-9]\)/\1/'             |
          sed 's/\([^0-9]\)0\{1,\}\([0-9]\)/\1\2/g' |
          tr ' ' '\n'                               |
          awk                                       '
            /^NF-[0-9]+\/NF-[0-9]+$/ {
              nfofs1 = substr($0,4,index($0,"/")-4) + 0;
              nfofs2 = substr($0,index($0,"/")+4) + 0;
              if (nfofs1 > nfofs2) {
                i = nfofs1;
                nfofs1 = nfofs2;
                nfofs2 = i;
              }
              for (i=nfofs1; i<=nfofs2; i++) {
                print "0 NF-" i;
              }
            }
            /^NF\/NF-[0-9]+$/ {
              nfofs2 = substr($0,index($0,"/")+4);
              print "0 NF";
              for (i=1; i<=nfofs2; i++) {
                print "0 NF-" i;
              }
            }
            /^NF-[0-9]+\/NF$/ {
              nfofs2 = substr($0,4,index($0,"/")-4) + 0;
              print "0 NF";
              for (i=1; i<=nfofs2; i++) {
                print "0 NF-" i;
              }
            }
            /^[0-9]+\/NF-[0-9]+$/ {
              printf("0 %s NF-%s\n",
                     substr($0,1,index($0,"/")-1),
                     substr($0,index($0,"/")+4)   );
            }
            /^NF-[0-9]+\/[0-9]+$/ {
              printf("0 %s NF-%s\n",
                     substr($0,index($0,"/")+1),
                     substr($0,4,index($0,"/")-4));
            }
            /^[0-9]+\/[0-9]+$/ {
              pos = index($0, "/");
              a = substr($0, 1, pos-1)+0;
              b = substr($0, pos+1)+0;
              if (a > b) {
                swp = a;
                a = b;
                b = swp;
              }
              for (i=a; i<=b; i++) {
                print 1, i;
              }
            }
            /^[0-9]+\/NF$/ {
              print 1, substr($0, 1, length($0)-3), "NF";
            }
            /^NF\/[0-9]+$/ {
              print 1, substr($0, index($0,"/")+1), "NF";
            }
            /^[0-9]+$/ {
              print 1, $0;
            }
            /^NF-[0-9]+$/ {
              print 0, $0;
            }
            (($0 == "NF") || ($0 == "NF/NF")) {
              print 0, "NF";
            }
          '                                         |
          sort -k 1,1 -k 2n,2 -k 3n,3               |
          uniq                                      |
          sed -n '1,/1 [0-9]\{1,\} NF$/p'           |
          awk                                       '
            BEGIN {
              f1_total  = 0;
              f2_max    = 0;
              f3_has_nf = 0;
            }
            {
              f1_total += $1; 
              if ($1 == 1) {
                f2_max = ($2 > f2_max) ? $2 : f2_max;
                f2_vals[$2] = 1;
              }
              f3_has_nf = ($3 == "NF") ? 1 : f3_has_nf;
              cell[NR,1] = $2;
              if (NF == 3) {
                cell[NR,2] = $3;
              }
            }
            END {
              if ((f1_total == NR) && (f3_has_nf)) {
                printf("split(\"\",mark);for(i=1;i<=NF;i++){mark[i]=1}");
                for (i=1; i<f2_max; i++) {
                  if (! (i in f2_vals)) {
                    printf("delete mark[%d];", i);
                  }
                }
              } else {
                printf("split(\"\",mark);");
                for (i=1; i<=NR; i++) {
                  if (i SUBSEP 2 in cell) {
                    printf("if(%s>%s){for(i=%s;i<=%s;i++){mark[i]=1}}else{for(i=%s;i<=%s;i++){mark[i]=1}}",
                           cell[i,1],cell[i,2],
                           cell[i,2],cell[i,1],
                           cell[i,1],cell[i,2]);
                  } else {
                    if (match(cell[i,1],/^[0-9]+$/) || (cell[i,1] == "NF")) {
                      printf("mark[%s]=1;",cell[i,1]);
                    } else {
                      printf("if(%s>0){mark[%s]=1}",cell[i,1],cell[i,1]);
                    }
                  }
                }
              }
              printf("convert_marked_flds();print;");
            }
          '                                         )
  if echo "$awkc0" | grep -q 'NF'; then
    awkc0b=''
  else
    awkc0b=${awkc0%convert_marked_flds*}
    awkc0='convert_marked_flds();print;'
  fi
else
  awkc0='print utf8zen2han($0);'
  awkc0b=''
fi

# === Generate the AWK code for han operation ========================
awkcode='
BEGIN {
  for (i=0; i<hdr_skip; i++) {
    if (getline line) {
      print line;
    } else {
      exit;
    }
  }
  utf8zen2han_prep();
  '"$awkc0b"'
}
{
  '"$awkc0"'
}
function convert_marked_flds( fld) {
  for (fld in mark) {
    $fld = utf8zen2han($fld);
  }
}
function utf8zen2han_prep() {

  # memorize all of the transforming letters
  z2h["　"]=" ";  z2h["！"]="!";  z2h["”"]="\""; z2h["＃"]="#";
  z2h["＄"]="$";  z2h["％"]="%";  z2h["＆"]="&";  z2h["’"]="'"'"'";
  z2h["（"]="(";  z2h["）"]=")";  z2h["＊"]="*";  z2h["＋"]="+";
  z2h["，"]=",";  z2h["－"]="-";  z2h["．"]=".";  z2h["／"]="/";
  z2h["０"]="0";  z2h["１"]="1";  z2h["２"]="2";  z2h["３"]="3";
  z2h["４"]="4";  z2h["５"]="5";  z2h["６"]="6";  z2h["７"]="7";
  z2h["８"]="8";  z2h["９"]="9";  z2h["："]=":";  z2h["；"]=";";
  z2h["＜"]="<";  z2h["＝"]="=";  z2h["＞"]=">";  z2h["？"]="?";
  z2h["＠"]="@";  z2h["Ａ"]="A";  z2h["Ｂ"]="B";  z2h["Ｃ"]="C";
  z2h["Ｄ"]="D";  z2h["Ｅ"]="E";  z2h["Ｆ"]="F";  z2h["Ｇ"]="G";
  z2h["Ｈ"]="H";  z2h["Ｉ"]="I";  z2h["Ｊ"]="J";  z2h["Ｋ"]="K";
  z2h["Ｌ"]="L";  z2h["Ｍ"]="M";  z2h["Ｎ"]="N";  z2h["Ｏ"]="O";
  z2h["Ｐ"]="P";  z2h["Ｑ"]="Q";  z2h["Ｒ"]="R";  z2h["Ｓ"]="S";
  z2h["Ｔ"]="T";  z2h["Ｕ"]="U";  z2h["Ｖ"]="V";  z2h["Ｗ"]="W";
  z2h["Ｘ"]="X";  z2h["Ｙ"]="Y";  z2h["Ｚ"]="Z";  z2h["［"]="[";
  z2h["＼"]="\\"; z2h["］"]="]";  z2h["＾"]="^";  z2h["＿"]="_";
  z2h["‘"]="`";  z2h["ａ"]="a";  z2h["ｂ"]="b";  z2h["ｃ"]="c";
  z2h["ｄ"]="d";  z2h["ｅ"]="e";  z2h["ｆ"]="f";  z2h["ｇ"]="g";
  z2h["ｈ"]="h";  z2h["ｉ"]="u";  z2h["ｊ"]="j";  z2h["ｋ"]="k";
  z2h["ｌ"]="l";  z2h["ｍ"]="m";  z2h["ｎ"]="n";  z2h["ｏ"]="o";
  z2h["ｐ"]="p";  z2h["ｑ"]="q";  z2h["ｒ"]="r";  z2h["ｓ"]="s";
  z2h["ｔ"]="t";  z2h["ｕ"]="u";  z2h["ｖ"]="v";  z2h["ｗ"]="w";
  z2h["ｘ"]="x";  z2h["ｙ"]="y";  z2h["ｚ"]="z";  z2h["｛"]="{";
  z2h["｜"]="|";  z2h["｝"]="}";  z2h["～"]="~";
                  z2h["。"]="｡";  z2h["「"]="｢";  z2h["」"]="｣";
  z2h["、"]="､";  z2h["・"]="･";  z2h["ヲ"]="ｦ";  z2h["ァ"]="ｧ";
  z2h["ィ"]="ｨ";  z2h["ゥ"]="ｩ";  z2h["ェ"]="ｪ";  z2h["ォ"]="ｫ";
  z2h["ャ"]="ｬ";  z2h["ュ"]="ｭ";  z2h["ョ"]="ｮ";  z2h["ッ"]="ｯ";
  z2h["ー"]="ｰ";  z2h["ア"]="ｱ";  z2h["イ"]="ｲ";  z2h["ウ"]="ｳ";
  z2h["エ"]="ｴ";  z2h["オ"]="ｵ";  z2h["カ"]="ｶ";  z2h["キ"]="ｷ";
  z2h["ク"]="ｸ";  z2h["ケ"]="ｹ";  z2h["コ"]="ｺ";  z2h["サ"]="ｻ";
  z2h["シ"]="ｼ";  z2h["ス"]="ｽ";  z2h["セ"]="ｾ";  z2h["ソ"]="ｿ";
  z2h["タ"]="ﾀ";  z2h["チ"]="ﾁ";  z2h["ツ"]="ﾂ";  z2h["テ"]="ﾃ";
  z2h["ト"]="ﾄ";  z2h["ナ"]="ﾅ";  z2h["ニ"]="ﾆ";  z2h["ヌ"]="ﾇ";
  z2h["ネ"]="ﾈ";  z2h["ノ"]="ﾉ";  z2h["ハ"]="ﾊ";  z2h["ヒ"]="ﾋ";
  z2h["フ"]="ﾌ";  z2h["ヘ"]="ﾍ";  z2h["ホ"]="ﾎ";  z2h["マ"]="ﾏ";
  z2h["ミ"]="ﾐ";  z2h["ム"]="ﾑ";  z2h["メ"]="ﾒ";  z2h["モ"]="ﾓ";
  z2h["ヤ"]="ﾔ";  z2h["ユ"]="ﾕ";  z2h["ヨ"]="ﾖ";  z2h["ラ"]="ﾗ";
  z2h["リ"]="ﾘ";  z2h["ル"]="ﾙ";  z2h["レ"]="ﾚ";  z2h["ロ"]="ﾛ";
  z2h["ワ"]="ﾜ";  z2h["ン"]="ﾝ";  z2h["゛"]="ﾞ";  z2h["゜"]="ﾟ";
  z2h["ガ"]="ｶﾞ"; z2h["ギ"]="ｷﾞ"; z2h["グ"]="ｸﾞ"; z2h["ゲ"]="ｹﾞ";
  z2h["ゴ"]="ｺﾞ"; z2h["ザ"]="ｻﾞ"; z2h["ジ"]="ｼﾞ"; z2h["ズ"]="ｽﾞ";
  z2h["ゼ"]="ｾﾞ"; z2h["ゾ"]="ｿﾞ"; z2h["ダ"]="ﾀﾞ"; z2h["ヂ"]="ﾁﾞ";
  z2h["ヅ"]="ﾂﾞ"; z2h["デ"]="ﾃﾞ"; z2h["ド"]="ﾄﾞ"; z2h["バ"]="ﾊﾞ";
  z2h["ビ"]="ﾋﾞ"; z2h["ブ"]="ﾌﾞ"; z2h["ベ"]="ﾍﾞ"; z2h["ボ"]="ﾎﾞ";
  z2h["パ"]="ﾊﾟ"; z2h["ピ"]="ﾋﾟ"; z2h["プ"]="ﾌﾟ"; z2h["ペ"]="ﾍﾟ";
  z2h["ポ"]="ﾎﾟ"; z2h["ヴ"]="ｳﾞ"; z2h["ヷ"]="ﾜﾞ"; z2h["ヺ"]="ｦﾞ";

  # memorize the characters for special transforming rule
  z2hd["カ"]=1; z2hd["キ"]=1; z2hd["ク"]=1; z2hd["ケ"]=1; z2hd["コ"]=1;
  z2hd["サ"]=1; z2hd["シ"]=1; z2hd["ス"]=1; z2hd["セ"]=1; z2hd["ソ"]=1;
  z2hd["タ"]=1; z2hd["チ"]=1; z2hd["ツ"]=1; z2hd["テ"]=1; z2hd["ト"]=1;
  z2hd["ハ"]=1; z2hd["ヒ"]=1; z2hd["フ"]=1; z2hd["ヘ"]=1; z2hd["ホ"]=1;
  z2hd["ウ"]=1; z2hd["ワ"]=1; z2hd["ヲ"]=1;

  # memorize groups
  z2hgroup[sprintf("\342\200")]=1; # E2 80 *
  z2hgroup[sprintf("\343\200")]=1; # E3 80 *
  z2hgroup[sprintf("\343\202")]=1; # E3 82 *
  z2hgroup[sprintf("\343\203")]=1; # E3 83 *
  z2hgroup[sprintf("\357\274")]=1; # EF BC *
  z2hgroup[sprintf("\357\275")]=1; # EF BD *
}

function utf8zen2han(s_in, i,s,s1,s2,s_out) {
  s_out = "";
  for (i=1; i<=length(s_in); i++) {
    s = substr(s_in,i,1);
    #if        (s < "\200") {
    #  s_out = s_out s;
    #  continue;
    #}
    if        (s < "\300") {
      s_out = s_out s;
    } else if (s < "\340") {
      i++;
      s_out = s_out s substr(s_in,i,1);
    } else if (s < "\360") {
      s1 = substr(s_in,i+1,1);
      s2 = substr(s_in,i+2,1);
      if (((s s1) in z2hgroup) && ((s s1 s2) in z2h)) {
        s_out = s_out z2h[s s1 s2];
        if ((s s1 s2) in z2hd) {          # Special Transforming Rule
          if (substr(s_in,i+3,3)=="″") { # for "Double Prime" Chr.
            s_out = s_out "ﾞ";            #
            i += 3;                       # (e.g.)
          }                               # "カ″" => "ｶﾞ"
        }                                 #
      } else {
        s_out = s_out s s1 s2;
      }
      i += 2;
    } else if (s < "\370") {
      s_out = s_out s substr(s_in,i+1,3);
      i += 3;
    } else if (s < "\374") {
      s_out = s_out s substr(s_in,i+1,4);
      i += 4;
    } else if (s < "\376") {
      s_out = s_out s substr(s_in,i+1,5);
      i += 5;
    } else {
      s_out = s_out s;
    }
  }
  return s_out;
}
'


######################################################################
# Main Routine
######################################################################

if [ $directmode -ne 0 ]; then
  printf '%s' "$directstr"         |
  awk -v hdr_skip=$opth "$awkcode"
else
  (cat "$file"; echo)              |
  awk -v hdr_skip=$opth "$awkcode" |
  awk 'BEGIN{
         ORS="";
         OFS="";
         getline line;
         print line;
         dlm="\n";
         while (getline line) {
           print dlm,line;
         }
       }
     '
fi
