#! /bin/sh

# designed by Nobuaki Tounaka
# written by 321516

# print the usage and exit
print_usage_and_exit () {
  cat <<-__USAGE 1>&2
	Usage   : ${0##*/} <n1> <n2> ...
	Version : Tue Jun 23 11:20:49 JST 2015
	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
__USAGE
  exit 1
}


# initialize
set -u
umask 0022
PATH='/usr/bin:/bin'
IFS=$(printf ' \t\n_'); IFS=${IFS%_}
export IFS LANG=C LC_ALL=C PATH

# parse arguments
case $# in 0) print_usage_and_exit;; esac

# make the formula
formula=$(printf '%s ' "$*"                     |
          tr '\t\n' '  '                        |
          grep -v '[^0-9. +-]'                  |
          sed 's/\([^ ]\{1,\}\) \{1,\}/(\1)+/g' |
          sed 's/+$//'                          )
case "$formula" in '') print_usage_and_exit;; esac

# calculating
awk "BEGIN{print $formula;}" 2>/dev/null

# exit
case $? in
  0) exit 0;;
  *) print_usage_and_exit;;
esac
