#! /bin/sh

# designed by Nobuaki Tounaka
# written by 321516

# print the usage and exit
print_usage_and_exit () {
  cat <<-__USAGE 1>&2
	Usage   : ${0##*/} <n1> <n2> ...
	Version : Sat Jun 20 00:30:58 JST 2015
	        : Open usp Tukubai (POSIX.1 Bourne Shell/POSIX.1 commands)
__USAGE
  exit 1
}


# initialize
set -u
umask 0022
PATH='/usr/bin:/bin'
IFS=$(printf ' \t\n_'); IFS=${IFS%_}
export IFS LANG=C LC_ALL=C PATH

# parse arguments
if [ $# -eq 0 ]; then
  print_usage_and_exit
fi
formula=''
for arg in "$@"; do
  if printf '%s\n' "$arg" | grep -Eq '^-?([0-9]+|[0-9]*\.[0-9]*)$'; then
    formula="$formula + $arg"
  else
    print_usage_and_exit
  fi
done

# plus
result=$(echo "${formula# + }" | bc | tr -d '\\\n')
if [ "${result#.}" != "$result" ]; then
  echo "0$result"
elif [ "${result#-.}" != "$result" ]; then
  echo "-0${result#-}"
else
  echo $result
fi
exit 0